action:test/publish-edge/release: create ~/bin/ directory before moving the spread binary
Test are failing due to
```
Running spread tests
mv: cannot move 'spread' to '/home/ubuntu/bin/spread': No such file or directory
Error: Process completed with exit code 1.
```

See: https://github.com/canonical/network-manager-snap/pull/56